name: FADA-3-Channel-Learning-Rate-Sweep
method: bayes
parameters:
  architecture:
    value: Linknet
  encoder:
    value: timm-regnetx_320
  in_channels:
    value: 3
  optimizer:
    value: Adam
  batch_size_source:
    value: 16
  batch_size_target:
    value: 8
  dataset_path:
    value: ./data/FIVES_random_crops_threshold01
  learning_rate_fea:
    min: 0.001
    max: 0.01
  learning_rate_cls:
    min: 0.001
    max: 0.01
  learning_rate_dis:
    min: 0.0001
    max: 0.001
  ndf:
    value: 512
  epochs:
    value: 10
  seg_loss:
    value: BCE
  pretrained:
    value: ./models/serene-sweep-9.pth
  gaussian:
    value: models/gaussianEncoder.pth
  augmented:
    value: true
metric:
  name: dice_score/target
  goal: maximize
