name: FADA-Gaussian-with-Prior-RingPenalizationWeight-Rate-Sweep
method: bayes
parameters:
  architecture:
    value: Linknet
  encoder:
    value: timm-regnetx_320
  in_channels:
    value: 3
  optimizer:
    value: Adam
  batch_size_source:
    value: 16
  batch_size_target:
    value: 8
  dataset_path:
    value: ./data/FIVES_random_crops_threshold01
  learning_rate_fea:
    value: 0.007053148664641283
  learning_rate_cls:
    value: 0.0014884108364363155
  learning_rate_dis:
    value: 0.00043925067706149473
  ndf:
    value: 512
  epochs:
    value: 10
  seg_loss:
    value: BCE
  pretrained:
    value: ./models/serene-sweep-9.pth
  gaussian:
    value: models/gaussianEncoder_with_priors.pth
  augmented:
    value: true
  contrastive_loss:
    value: true
  penalize_rings_weight:
    min: 0
    max: 10
metric:
  name: dice_score/target
  goal: maximize
