name: FADA-RGB-Learning-Rate-Sweep-Handpicked-Channels
method: bayes
parameters:
  architecture:
    value: Linknet
  encoder:
    value: timm-regnetx_320
  in_channels:
    value: 3
  optimizer:
    value: Adam
  batch_size_source:
    value: 16
  batch_size_target:
    value: 8
  dataset_path:
    value: ./data/FIVES_random_crops_threshold01
  learning_rate_fea:
    min: 0.001
    max: 0.01
  learning_rate_cls:
    min: 0.001
    max: 0.01
  learning_rate_dis:
    min: 0.0001
    max: 0.001
  ndf:
    value: 512
  epochs:
    value: 10
  seg_loss:
    value: BCE
  augmented:
    value: true
  rgb:
    value: true
  pretrained:
    value: ./models/serene-sweep-9.pth
  rgb_channels:
    value: [335, 267, 131]

metric:
  name: dice_score/target
  goal: maximize
