name: Approach-9-Grayscale-CycleGAN-1x1Conv-validation_1
method: random
parameters:
  architecture:
    value: Linknet
  encoder:
    value: timm-regnetx_320
  in_channels:
    value: 1
  optimizer:
    value: Adam
  batch_size_source:
    value: 16
  batch_size_target:
    value: 8
  dataset_path:
    value: ./data/FIVES_random_crops_threshold01
  learning_rate_fea:
    min: 0.001
    max: 0.01
  learning_rate_cls:
    min: 0.001
    max: 0.01
  learning_rate_dis:
    min: 0.0001
    max: 0.001
  ndf:
    value: 512
  epochs:
    value: 10
  seg_loss:
    value: BCE
  pretrained:
    value: ./models/Linknet-timm-regnetx_320-512x512-augmented-with-random-crops-single-channel-focal.pth
  augmented:
    value: true
  choose_indices:
    value: [1]
  feature_conv_reducer:
    value: 1x1conv
  cycle_loss_hyperparams:
    parameters:
      lr_F:
        min: 0.001
        max: 0.01
      lr_G:
        min: 0.001
        max: 0.01
      lambda_G:
        min: 0.1
        max: 1.0
      lambda_F:
        min: 0.1
        max: 1.0
metric:
  name: test/dice_score_postprocessed
  goal: maximize
